### PR TITLE
Remove the block binding

### PR DESCRIPTION
**Pull request by carolinan**
**Description**
This PR removes the copyright block binding because the format of the copyright notice is incorrect.
The copyright notice in the footers is replaced with the theme name.

Partial for https://github.com/WordPress/twentytwentyfive/issues/571

**Testing Instructions**

Confirm that the theme name is showing at the bottom left of
- The default footer
- Footer with columns
- Footer with newsletter signup

And in the Portfolio homepage template.

### CODE REVIEW

**Review by juanfra — COMMENTED** [review]
Thanks for the changes, works well! The only thing I'm doubtful is if we have to pass `Twenty Twenty-Five` to translation functions. I believe, just like `WordPress`, these stay the same in every language and that's the intention.

https://github.com/user-attachments/assets/b48799dc-ec1f-4270-95ad-104b0d61a76a

**Comment by carolinan** [comment]
The way it was explained to me many many years ago was that it needs to be translation ready because the script is different. WordPress in for example Arabic is `ووردبريس`  but an URL like wordpress.org is wordpress.org

**Comment by 2ndkauboy** [comment]
Wouldn't it make more sense to use the "Site Title" instead of the theme name? Only in some footers we would have the site title twice then.

I don't really think the theme name - with no link - does make sense for most users. The site name kind of makes sense.

Or just don't have the whole "left column" at all, if it would duplicate the site title? :thinking:

**Comment by carolinan** [comment]
I agree with using the site title, or even using the site tagline, but I know that @beafialho asked for the theme name.

**Comment by carolinan** [comment]
In my opinion if the left side was left empty it may look unbalanced

**Comment by 2ndkauboy** [comment]
@carolinan this is what I've meant: https://github.com/WordPress/twentytwentyfive/pull/578

**Comment by juanfra** [comment]
> The way it was explained to me many many years ago was that it needs to be translation ready because the script is different. WordPress in for example Arabic is `ووردبريس` but an URL like wordpress.org is wordpress.org

Thanks for clarifying, Carolina!

Regarding having the site title, as mentioned, it was discussed and the problem is redundancy. It'd be displayed two times in a small piece of "real estate". 

> In my opinion if the left side was left empty it may look unbalanced

I fully agree with this.

If we want to discuss the modification of the footer, I'd suggest we open a new issue and discuss it there. @beafialho carefully crafted the design of the different footers (and the theme!), so I'd prefer if we ran any of these things with her first.

**Comment by beafialho** [comment]
The footer was designed to have the site title (above) and the theme name showing discretely at the bottom (like many other themes do). I suggest we keep it like that.

Captura de ecrã 2024-10-16, às 10 13 58

**Comment by beafialho** [comment]
We could however, for clarity, add `Twenty Twenty-Five Theme` instead of only `Twenty Twenty-Five`. I realise it may be somewhat abstract for users who aren't familiar with WordPress' default themes.

**Comment by juanfra** [comment]
I'd personally prefer just `Twenty Twenty-Five`, but I could be biased as I believe `Twenty Twenty-Five Theme` wouldn't translate well to Spanish.

**Comment by juanfra** [comment]
Thanks again Carolina, let's move forward with the theme name translated for now. And in case we need to make an adjustment we can revisit it later. Thank you all!

**Pull request merged**
