### PR TITLE
Complex (news) blog: Home

### PR DESCRIPTION
**Pull request by amitbajracharya**
1. I have created the layout for the figma file: Complex Blog: Home
2. I used offset to display the blog post in the hero section as well as the blog list below it.
3. I have updated theme.json as well to match with the design.
4. I have not added any custom style yet, may be we will need that as well for the mobile version.

### CODE REVIEW

**Comment by carolinan** [comment]
Hi @amitbajracharya 
Thank you for working on this.

To be able to switch between different designs for the templates, this needs to be created as a pattern, not HTML template.

Please see https://github.com/WordPress/twentytwentyfive/issues/42

The index file is a fall back that WordPress uses when other templates are missing, and it should not be changed in this PR.

The PR has many unrelated changes to theme.json. Please only include the changes required by the new pattern.

As recommended in https://github.com/WordPress/twentytwentyfive/issues/29
please keep the "pipe" format for the presets.

**Comment by kafleg** [comment]
@amitbajracharya Let's start creating patterns first. So that we can use those patterns in the templates file.

**Comment by amitbajracharya** [comment]
Thank you guys for the feedback. I can create a pattern for them.
One question, are we going with the Offset post approach?

**Comment by carolinan** [comment]
> Thank you guys for the feedback. I can create a pattern for them. One question, are we going with the Offset post approach?

I don't think there are any other options?

**Comment by juanfra** [comment]
@amitbajracharya thank you for working on this. Can you please rebase and resolve merge conflicts so we can keep moving forward with this one?

**Comment by amitbajracharya** [comment]
Sure @juanfra  I will work on it. I will push the update by this week.

**Comment by amitbajracharya** [comment]
I have included the patterns in index.html. Me and @kafleg met over a call today and surprisingly the pattern that I included is visible to @kafleg 's editor however, in my editor it says "Pattern Placeholder" only. And there is no option to reset in the template as well. Any idea?

image

**Comment by carolinan** [comment]
Are you using WordPress 6.6.x? Did you disable all plugins except Gutenberg?

**Comment by carolinan** [comment]
The pull request must not change any HTML files. Users select the alternative patterns by switching the design using options in the interface.

**Comment by amitbajracharya** [comment]
@carolinan  yes, I am using WordPress 6.6 and I have not installed any other plugins in this project.

image

**Comment by carolinan** [comment]
If there is no reset option, it is because there are no changes saved to the database 🤷

**Comment by kafleg** [comment]
> If there is no reset option, it is because there are no changes saved to the database 🤷

We deleted the repository and cloned again. The issue got resolved. May be there was issues in the last cloned repo.

**Comment by carolinan** [comment]
@amitbajracharya Hi, I am closing this PR since another PR has been opened that include the markup for **_all_** the news blog templates.
https://github.com/WordPress/twentytwentyfive/pull/155

**Pull request closed without merging**
