### PR TITLE
Theme.json visual adjustments for quote, pullquote, cite & code block

### PR DESCRIPTION
**Pull request by beafialho**
This PR addresses #501 and adds an enhancement to the code. This is the intended look of the blocks worked on:

- Improved letter spacing, font size and font weights

Captura de ecrã 2024-10-08, às 09 40 27

Captura de ecrã 2024-10-08, às 09 40 31

Captura de ecrã 2024-10-08, às 09 41 25

### CODE REVIEW

**Comment by carolinan** [comment]
@beafialho All other presets and the combined variations are unchanged, is that correct?

**Comment by carolinan** [comment]
I am seeing some duplicates, there are presets that set the cite to font size small and font weight 300, these can be removed since they now match theme.json.

**Comment by beafialho** [comment]
Correct @carolinan, I only changed the default one. However, now that I tried it, the Evening variation should have the same the same settings, since the only thing varying is its colors.

**Comment by carolinan** [comment]
I think I have found and removed all duplicate styles.

**Comment by carolinan** [comment]
@juanfra Aside, I think we can remove all `"fontStyle": "normal"` since this is the default.
The only place where it is needed is in theme.json settings > typography > fontfamilies

**Comment by beafialho** [comment]
Thank you for the help! Looking good 🚀

**Review by juanfra — APPROVED** [review]
Thank you, looks good to me 🫡

**Pull request merged**
