### PR TITLE
Try: Post format binding.

### PR DESCRIPTION
**Pull request by juanfra**
**Description**

Cherry-picking the post format binding from https://github.com/WordPress/twentytwentyfive/pull/576

**Screenshots**

N/A

**Testing Instructions**

1. Create one or more posts with formats.
2. Insert the pattern where you want to test it, in a template, or content.

### CODE REVIEW

**Comment by carolinan** [comment]
oops :p

**Comment by carolinan** [comment]
I closed mine, I was too slow.

It needs a category and description.

**Comment by juanfra** [comment]
Thanks Carolina, added the categories and description.

**Comment by carolinan** [comment]
Hmm are we keeping the pattern as small text? I don't have a strong feeling about it.

**Comment by juanfra** [comment]
Maybe we can merge it as is, so that we have it in, and then run it by Bea so that she can decide?

**Comment by carolinan** [comment]
Ah, the hook is missing, I am getting "Invalid source" under "Attributes" in the block editor.

**Comment by juanfra** [comment]
Thanks! I pushed the changes.

**Comment by carolinan** [comment]
Thank you.

**Comment by juanfra** [comment]
Thank _you_!

**Pull request merged**
