### PR TITLE
Change/image names

### PR DESCRIPTION
**Pull request by troychaplin**
**Description**

Updating image names as per the discussion in [issue 589](https://github.com/WordPress/twentytwentyfive/issues/589)

### CODE REVIEW

**Review by juanfra — COMMENTED** [review]
Looking great! Thank you

Can you please add `red-hibiscus-closeup.webp` to line 180 of the readme? Apart from that everything looks good to me.

**Comment by troychaplin** [comment]
> Looking great! Thank you
> 
> Can you please add `red-hibiscus-closeup.webp` to line 180 of the readme? Apart from that everything looks good to me.

For sure, will be fixed in about a half hour when I get home

**Comment by troychaplin** [comment]
@juanfra image reference added to the readme as requested

**Review by juanfra — APPROVED** [review]
Thanks so much @troychaplin - Looks good to me

**Pull request merged**
