### PR TITLE
Added comments to all single templates

### LINKED ISSUE #245: Add comments section to all "single" templates
**Description**

We need to add the comments section to all "single" templates.

Right now the comments template needs to be added to the following templates:

- [ ] News blog single post with sidebar.
- [ ] Photo blog single post.
- [ ] Text only blog single post.
- [ ] Right aligned single post.

### PR DESCRIPTION
**Pull request by eirichmond**
**Description**

To add comments to "single" templates

**Screenshots**

https://github.com/user-attachments/assets/088f6788-0548-4012-8716-1e7dd9cac906

**Testing Instructions**

Got to Site Editor
Select Single Post template
To view comments select Design for:
> News blog single post with sidebar.
> Photo blog single post.
> Text only blog single post.
> Right aligned single post.

### CODE REVIEW

**Comment by carolinan** [comment]
Please see the comment on https://github.com/WordPress/twentytwentyfive/pull/257.

The templates need to reuse the existing pattern for the comments, to reduce the maintenance burden of needing to update the same code in multiple places.

**Comment by eirichmond** [comment]
> Please see the comment on #257.
> 
> The templates need to reuse the existing pattern for the comments, to reduce the maintenance burden of needing to update the same code in multiple places.

Ah apologies, not sure what I was thinking there!

**Comment by eirichmond** [comment]
Closing this PR to avoid confusion with #257

**Comment by eirichmond** [comment]
Reclosing this PR to avoid confusion with https://github.com/WordPress/twentytwentyfive/pull/257

**Pull request closed without merging**
