### PR TITLE
Add, test, and adjust pattern viewport widths #310

### PR DESCRIPTION
**Pull request by noruzzamans**
@carolinan I have added viewport widths for all patterns. Please review and let me know if any changes are needed. Thanks

### CODE REVIEW

**Comment by carolinan** [comment]
All? Why? Please understand that there is no way that anyone is able to review 62 patterns in one PR. 😃

**Comment by carolinan** [comment]
Each pattern needs to be considered individually, it is unlikely that one size will fit all.
This is also why I asked to please include before and after screenshots of the pattern preview.

**Comment by carolinan** [comment]
All of these patterns also have Inserter:no added, which means that the user wont be able to use any of them.

**Comment by carolinan** [comment]
I am going to close this, the addition of the viewport width setting needs to be deliberate.

**Comment by noruzzamans** [comment]
> I am going to close this, the addition of the viewport width setting needs to be deliberate.

its okay

**Pull request closed without merging**
