### PR TITLE
Add optional color palettes

### LINKED ISSUE #24: Add default and optional color palettes
This is a tracking issue for adding color palettes.
**Note that all colors and slugs listed here may be iterated on during the process.**

## Colors used in the default style

FIgma: https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=3112-260&t=qC1CDiog2u4tpIsg-4

In Figma, the default color palette is presented as

Primary `#111111`
Background `#FFFFFF`
Secondary `#686868`
Tertiary `#FBFAF3`
Opacity 20% `#FFFFFF33`
Accent 1 `#FFEE58`
Accent 2 `#F6CFF4`
Accent 3 `#503AA8`

To make it smoother to switch themes, my suggestion would be to:
- Change "Primary"  to "Contrast"
- Change "Background" to "Base"
- Change "Secondary" to " Contrast two"
- Change "Tertiary" to "Contrast three"

Here is a table with a comparison with Twenty Twenty-Four just to compare the color names/slugs
| Twenty Twenty-Five | Twenty Twenty-Four Color Palette  |
|--------------------|----------------------------------|
|  Base `#FFFFFF` | Base - `#f9f9f9`               |
|     -               | Base / Two - `#ffffff`         |
|  Contrast `#111111`  | Contrast - `#111111`           |
|  Contrast / Two `#686868`    | Contrast / Two - `#636363`     |
|  Contrast/ Three `#FBFAF3`   | Contrast / Three - `#A4A4A4`   |
|  Accent `#FFEE58`  | Accent - `#cfcabe`   |
|  Accent / Two `#F6CFF4`  | Accent / Two - `#c2a990`       |
|  Accent / Three `#503AA8`   | Accent / Three - `#d8613c`     |
|  - | Accent / Four - `#b1c5a4`      |

----

## Color palette presets

**WIP: These are not complete**

Color palette presets are partial .json files that only contain color settings.
Each preset uses its own file.
Each file needs to include version, schema, slug, and title.
The files need to be placed in the styles folder, but it is also possible to organize the files using subfolders, for example
styles/color.

### Manrope + Manrope (Dark mode)
Contrast `#D1D1D1`
Base `#1B1B1B`
Accent 1 `#6F6720`
Accent 2 `#CFBEE4`
Accent 3 `#3F3272`

### Beirut & Literata 60P
Contrast `#5F5F5F`
Base `#F8F7F5`
Accent 1 `#FFFFFF`
Accent 2 `#914D0E`
Accent 3 `#191919`

### Volkorn and Fira code
Contrast `#3B3B3B`
Base `#E2E2E2`
Accent 1 `#F5EDFF`
Accent 2 `#650DD4`
Accent 3 `#191919`

### Platypi + Ysabeau Office
Contrast `#516028`
Base `#DAE7BD`
Accent 1 `#EBF6D3`
Accent 2 `#C7F642`
Accent 3 `#303D10`

### Roboto Slab + Manrope
Contrast `#FFFFFF`
Base `#131313`
Accent 1 `#4B52FF`
Accent 2 `#252525`
Accent 3 `#FF6442`

### Literata 60pt + Ysabeau Office
Contrast `#57544B`
Base `#DFDCD7`
Accent 1 `#182949`
Accent 2 `#7A9BDB`
Accent 3 `#F8F5F0`

### Platypi + Literata 60pt
Contrast `#DB9AB1`
Base `#330616`
Accent 1 `#F0FDA6`
Accent 2 `#C1E4E7`
Accent 3 `#DB9AB1`

### Literata 60pt + Fira Sans
Contrast) `#79F3B1`
Base `#4433A6`
Accent 1 `#4433A6`
Accent 2 `#79F3B1`
Accent 3 `#251D51`

### PR DESCRIPTION
**Pull request by efu98**
Resolves #24 
Added optional color palettes to the theme

**Screenshots**
Capture d’écran 2024-08-26 à 23 24 10

**Testing Instructions**

1. Activate the theme
2. Customize theme 
3. Go to styles
4. There should be 9 different palettes

### CODE REVIEW

**Comment by carolinan** [comment]
Hi, can you pull the latest changes from trunk, so that the color palette can be tested easier with the templates?

**Comment by carolinan** [comment]
The preview of the palette in the option only shows five colors, so the palettes look very similar.
If you move the accent colors before primary, the accent colors will show in the option.

**Comment by efu98** [comment]
@carolinan Hello, i have merged trunk into the PR and re-ordered the colours :)

**Comment by carolinan** [comment]
I saw your question, but lets merge this so that it can be tested and used, and iterate when or if needed.
Thank you.

**Pull request merged**
