### PR TITLE
Block style: Code 

### LINKED ISSUE #127: Block style: Code
**Is your feature request related to a problem? Please describe.**

Add the default style for the code block to theme.json.
The background color should be `secondary`, and the text color should be `contrast`.
Font size should be `small`. Font weight `400`. The font family should not be set, the block can fallback to the default. 
The left, right, top and bottom padding should be `small`.

[Figma design](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=565-10056&m=dev)

(Note that the design in Figma uses other color names)

### PR DESCRIPTION
**Pull request by kishanjasani**
**Description**
Update the styles for the default code block. Fixes: #127 

**Screenshots**
Screenshot at Aug 28 09-22-53

**Testing Instructions**

1. Add page
2. Add code block to the page and check the styles.

### CODE REVIEW

**Review by juanfra — COMMENTED** [review]
Thanks for working on this. The changes look good ✨

The only thing I noticed is that the figma is using the `SF Mono` font and given that we're not including it, the code block is defaulting to `monospace`. 

@beafialho are we ok using `monospace` here?

**Comment by beafialho** [comment]
We could perhaps use `Fira Code`, since we're including it in the theme?

**Comment by juanfra** [comment]
Thanks Bea! Sounds good to me. @kishanjasani can you please work on the adjustments?

**Comment by kishanjasani** [comment]
Updated the fonts to `fira-code`.

**Pull request merged**
