### PR TITLE
Tweak variations to remove explicit color references 

### LINKED ISSUE #620: Difficult to modify colors when a section style is applied
In some variations, the section styles are forcing an explicit color values. The result of this is that the colors are visually the same to start with, but when you change the "Text" color in the inspector, the links, headings, etc values all remain using the fixed value. 

Wherever possible, these should reference the current text color, rather than explicit colors.

### PR DESCRIPTION
**Pull request by richtabor**
**Description**

Closes #620.

Using `currentColor` allows for colors to be manipulated manually within the Inspector. Otherwise users are required to modify text and link colors, which feels broken as the text and link colors are the same value to start.

**Testing Instructions**

Test each color and full style variation across each section style.

### CODE REVIEW

**Comment by carolinan** [comment]
Please show that all the color contrasts have been tested.

**Comment by richtabor** [comment]
> Please show that all the color contrasts have been tested.

I asked @beafialho to review, thanks.

**Comment by beafialho** [comment]
I noticed a few places where links seem to have specific settings and aren't contrasting:

- **Noon:** Site Title, Title (Post title), Comments Title, Comment Author, Comment Date, Comment Reply Link, Comment Edit Link and Post Date
- **Midnight, Afternoon, Evening, Twilight:** Comment Author, Comment Date, Comment Reply Link, Comment Edit Link and Post Date
- **Dusk, Sunrise, Morning:** Comment Author, Comment Date and Post Date

**Review by juanfra — COMMENTED** [review]
Thanks for working on this, Rich! It's looking good.

I've been through the different variations, and here are my findings:

**Evening**

- Style 3 - link - Very low contrast (3.24:1)
- Style 4 - link - Very low contrast (1.07:1)
- Style 5 - link - Very low contrast (1.42:1)

| Before | After |
| --- | --- |
| evening-before | evening-after |


**Noon**

- Style 4 - Headings - Very low contrast (1:1)
- Style 5 - Headings - Very low contrast (1:1)

| Before | After |
| --- | --- |
| noon-before | noon-after |

**Comment by juanfra** [comment]
@richtabor @beafialho I've pushed a commit with changes to fix the parity that we had since [this PR](https://github.com/WordPress/twentytwentyfive/pull/635), and that should also be fixing the contrast issues I've found.

Rich, feel free to revert if you find any issues. Bea, if you can please give this another go and see if everything looks good on your end.

Thanks 🙌

**Comment by beafialho** [comment]
Thank you!

I only noticed issues in Noon Section Style 4 (the one with a black background). I believe it must be because Noon has the **Headings** and **Post Titles** color defined as `#191919`. They should indeed be that color, do you think there's a way to keep that color but make it work on this section style? If not, we can adjust accordingly but just to try to stick with the design intention.

https://github.com/user-attachments/assets/50d5fc18-2f0b-47e8-a428-88d1fea5a289

**Comment by juanfra** [comment]
Thanks @beafialho - I just pushed a change that should fix that.

**Comment by beafialho** [comment]
Thank you @juanfra, the issues I mentioned in Noon are solved now!

**Comment by beafialho** [comment]
Can we also make sure the Quote block's colors are looking/working ideally? For [more context](https://github.com/WordPress/twentytwentyfive/pull/654#issuecomment-2446357876).

**Comment by juanfra** [comment]
@beafialho I just pushed a change that should fix the quote block issue for all sections in all variations.

https://github.com/user-attachments/assets/6e617f21-0c5e-492e-a0d2-b99edb802b53

**Comment by beafialho** [comment]
Thank you for your patience on this one @juanfra. This one is a tricky one to test because you need to have all the blocks listed out on the same page to get the view. I have noticed on my site that Post Date is still using a fixed color and Pullquote seems too as well. 🫠

Captura de ecrã 2024-10-30, às 14 42 02
Captura de ecrã 2024-10-30, às 14 46 11

I'm not sure about the Code block, but it seems to have a fixed color as well:

https://github.com/user-attachments/assets/a067963c-581a-4011-ba1b-9ef289610e6b

 Apologies for the back and forth but hopefully after these are addressed this is ready to merge.

**Comment by juanfra** [comment]
@beafialho I pushed a fix for the pullquote in the different section styles.

Could you please clarify the expected behavior for the code and post-date blocks? Where are you taking those screencasts from?

**Comment by beafialho** [comment]
> Could you please clarify the expected behavior for the code and post-date blocks? Where are you taking those screencasts from?

The Code block should always have a slightly lighter or darker color than the background (usually Tertiary). And the Post Date should just have an accessible color.

**Comment by carolinan** [comment]
I have seen the code block issue: I let it slide because the **text** is always visible on all variations, so it is still accessible.

**Comment by beafialho** [comment]
Yes, the code block isn't necessarily a bug because it is readable.

**Comment by juanfra** [comment]
Ok, I pushed changes for the date block, and left the code block as is. For the date block on different sections, I chose the current color at 85%.

<details>
<summary>Code to test</summary>

```
<!-- wp:group {"metadata":{"name":"Style 1"},"className":"is-style-section-1","style":{"spacing":{"padding":{"top":"var:preset|spacing|30","bottom":"var:preset|spacing|30","left":"var:preset|spacing|30","right":"var:preset|spacing|30"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group is-style-section-1" style="padding-top:var(--wp--preset--spacing--30);padding-right:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--30);padding-left:var(--wp--preset--spacing--30)"><!-- wp:paragraph -->
<p>Style 1</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"metadata":{"name":"Style 2"},"className":"is-style-section-2","style":{"spacing":{"padding":{"top":"var:preset|spacing|30","bottom":"var:preset|spacing|30","left":"var:preset|spacing|30","right":"var:preset|spacing|30"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group is-style-section-2" style="padding-top:var(--wp--preset--spacing--30);padding-right:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--30);padding-left:var(--wp--preset--spacing--30)"><!-- wp:paragraph -->
<p>Style 2</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"metadata":{"name":"Style 3"},"className":"is-style-section-3","style":{"spacing":{"padding":{"top":"var:preset|spacing|30","bottom":"var:preset|spacing|30","left":"var:preset|spacing|30","right":"var:preset|spacing|30"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group is-style-section-3" style="padding-top:var(--wp--preset--spacing--30);padding-right:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--30);padding-left:var(--wp--preset--spacing--30)"><!-- wp:paragraph -->
<p>Style 3</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"metadata":{"name":"Style 4"},"className":"is-style-section-4","style":{"spacing":{"padding":{"top":"var:preset|spacing|30","bottom":"var:preset|spacing|30","left":"var:preset|spacing|30","right":"var:preset|spacing|30"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group is-style-section-4" style="padding-top:var(--wp--preset--spacing--30);padding-right:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--30);padding-left:var(--wp--preset--spacing--30)"><!-- wp:paragraph -->
<p>Style 4</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"metadata":{"name":"Style 5"},"className":"is-style-section-5","style":{"spacing":{"padding":{"top":"var:preset|spacing|30","bottom":"var:preset|spacing|30","left":"var:preset|spacing|30","right":"var:preset|spacing|30"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group is-style-section-5" style="padding-top:var(--wp--preset--spacing--30);padding-right:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--30);padding-left:var(--wp--preset--spacing--30)"><!-- wp:paragraph -->
<p>Style 5</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"is-style-default","layout":{"type":"constrained"}} -->
<div class="wp-block-group is-style-default"><!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button">Standard button</a></div>
<!-- /wp:button -->

<!-- wp:button {"className":"is-style-outline"} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link wp-element-button">Outline</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"is-style-section-1","style":{"spacing":{"padding":{"top":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|50","right":"var:preset|spacing|50"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group is-style-section-1" style="padding-top:var(--wp--preset--spacing--50);padding-right:var(--wp--preset--spacing--50);padding-bottom:var(--wp--preset--spacing--50);padding-left:var(--wp--preset--spacing--50)"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Heading - Style 1</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Section style 1 (but with extra padding...). And <a href="#">a link</a></p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"flex","orientation":"vertical"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"className":"is-style-pill is-style-text-annotation"} -->
<p class="is-style-pill is-style-text-annotation">Annotation style</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="#">A standard button</a></div>
<!-- /wp:button -->

<!-- wp:button {"className":"is-style-outline"} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link wp-element-button" href="#">An outlined button</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons -->

<!-- wp:quote -->
<blockquote class="wp-block-quote"><!-- wp:paragraph {"style":{"typography":{"writingMode":"horizontal-tb"}}} -->
<p style="writing-mode:horizontal-tb">“Early in my career...I had to choose between an honest <a href="http://blocks.local/section-styles/" data-type="page" data-id="3437">arrogance</a> and a hypercritical humility... I deliberately choose an honest arrogance, and I've never been sorry.”</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"fontSize":"small"} -->
<p class="has-small-font-size">Frank Lloyd Wright</p>
<!-- /wp:paragraph --></blockquote>
<!-- /wp:quote -->

<!-- wp:pullquote -->
<figure class="wp-block-pullquote"><blockquote><p>“Early in my career...I had to choose between an honest <a href="http://blocks.local/section-styles/" data-type="page" data-id="3437">arrogance</a> and a hypercritical humility... I deliberately choose an honest arrogance, and I've never been sorry.”</p><cite>Frank Lloyd Wright</cite></blockquote></figure>
<!-- /wp:pullquote -->

<!-- wp:post-date /--></div>
<!-- /wp:group -->

<!-- wp:group {"className":"is-style-section-2","style":{"spacing":{"padding":{"top":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|50","right":"var:preset|spacing|50"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group is-style-section-2" style="padding-top:var(--wp--preset--spacing--50);padding-right:var(--wp--preset--spacing--50);padding-bottom:var(--wp--preset--spacing--50);padding-left:var(--wp--preset--spacing--50)"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Heading - Style 2</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Section style 2 (but with extra padding...). And <a href="#">a link</a></p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"flex","orientation":"vertical"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"className":"is-style-pill is-style-text-annotation"} -->
<p class="is-style-pill is-style-text-annotation">Annotation style</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="#">A standard button</a></div>
<!-- /wp:button -->

<!-- wp:button {"className":"is-style-outline"} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link wp-element-button" href="#">An outlined button</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons -->

<!-- wp:quote -->
<blockquote class="wp-block-quote"><!-- wp:paragraph {"style":{"typography":{"writingMode":"horizontal-tb"}}} -->
<p style="writing-mode:horizontal-tb">“Early in my career...I had to choose between an honest <a href="http://blocks.local/section-styles/" data-type="page" data-id="3437">arrogance</a> and a hypercritical humility... I deliberately choose an honest arrogance, and I've never been sorry.”</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"fontSize":"small"} -->
<p class="has-small-font-size">Frank Lloyd Wright</p>
<!-- /wp:paragraph --></blockquote>
<!-- /wp:quote -->

<!-- wp:pullquote -->
<figure class="wp-block-pullquote"><blockquote><p>“Early in my career...I had to choose between an honest <a href="http://blocks.local/section-styles/" data-type="page" data-id="3437">arrogance</a> and a hypercritical humility... I deliberately choose an honest arrogance, and I've never been sorry.”</p><cite>Frank Lloyd Wright</cite></blockquote></figure>
<!-- /wp:pullquote -->

<!-- wp:post-date /--></div>
<!-- /wp:group -->

<!-- wp:group {"className":"is-style-section-3","style":{"spacing":{"padding":{"top":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|50","right":"var:preset|spacing|50"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group is-style-section-3" style="padding-top:var(--wp--preset--spacing--50);padding-right:var(--wp--preset--spacing--50);padding-bottom:var(--wp--preset--spacing--50);padding-left:var(--wp--preset--spacing--50)"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Heading - Style 3</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Section style 3 (but with extra padding...). And <a href="#">a link</a></p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"flex","orientation":"vertical"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"className":"is-style-pill is-style-text-annotation"} -->
<p class="is-style-pill is-style-text-annotation">Annotation style</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="#">A standard button</a></div>
<!-- /wp:button -->

<!-- wp:button {"className":"is-style-outline"} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link wp-element-button" href="#">An outlined button</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons -->

<!-- wp:quote -->
<blockquote class="wp-block-quote"><!-- wp:paragraph {"style":{"typography":{"writingMode":"horizontal-tb"}}} -->
<p style="writing-mode:horizontal-tb">“Early in my career...I had to choose between an honest <a href="http://blocks.local/section-styles/" data-type="page" data-id="3437">arrogance</a> and a hypercritical humility... I deliberately choose an honest arrogance, and I've never been sorry.”</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"fontSize":"small"} -->
<p class="has-small-font-size">Frank Lloyd Wright</p>
<!-- /wp:paragraph --></blockquote>
<!-- /wp:quote -->

<!-- wp:pullquote -->
<figure class="wp-block-pullquote"><blockquote><p>“Early in my career...I had to choose between an honest <a href="http://blocks.local/section-styles/" data-type="page" data-id="3437">arrogance</a> and a hypercritical humility... I deliberately choose an honest arrogance, and I've never been sorry.”</p><cite>Frank Lloyd Wright</cite></blockquote></figure>
<!-- /wp:pullquote -->

<!-- wp:post-date /--></div>
<!-- /wp:group -->

<!-- wp:group {"className":"is-style-section-4","style":{"spacing":{"padding":{"top":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|50","right":"var:preset|spacing|50"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group is-style-section-4" style="padding-top:var(--wp--preset--spacing--50);padding-right:var(--wp--preset--spacing--50);padding-bottom:var(--wp--preset--spacing--50);padding-left:var(--wp--preset--spacing--50)"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Heading - Style 4</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Section style 4 (but with extra padding...). And <a href="#">a link</a></p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"flex","orientation":"vertical"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"className":"is-style-pill is-style-text-annotation"} -->
<p class="is-style-pill is-style-text-annotation">Annotation style</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="#">A standard button</a></div>
<!-- /wp:button -->

<!-- wp:button {"className":"is-style-outline"} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link wp-element-button" href="#">An outlined button</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons -->

<!-- wp:quote -->
<blockquote class="wp-block-quote"><!-- wp:paragraph {"style":{"typography":{"writingMode":"horizontal-tb"}}} -->
<p style="writing-mode:horizontal-tb">“Early in my career...I had to choose between an honest <a href="http://blocks.local/section-styles/" data-type="page" data-id="3437">arrogance</a> and a hypercritical humility... I deliberately choose an honest arrogance, and I've never been sorry.”</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"fontSize":"small"} -->
<p class="has-small-font-size">Frank Lloyd Wright</p>
<!-- /wp:paragraph --></blockquote>
<!-- /wp:quote -->

<!-- wp:pullquote -->
<figure class="wp-block-pullquote"><blockquote><p>“Early in my career...I had to choose between an honest <a href="http://blocks.local/section-styles/" data-type="page" data-id="3437">arrogance</a> and a hypercritical humility... I deliberately choose an honest arrogance, and I've never been sorry.”</p><cite>Frank Lloyd Wright</cite></blockquote></figure>
<!-- /wp:pullquote -->

<!-- wp:post-date /--></div>
<!-- /wp:group -->

<!-- wp:group {"className":"is-style-section-5","style":{"spacing":{"padding":{"top":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|50","right":"var:preset|spacing|50"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group is-style-section-5" style="padding-top:var(--wp--preset--spacing--50);padding-right:var(--wp--preset--spacing--50);padding-bottom:var(--wp--preset--spacing--50);padding-left:var(--wp--preset--spacing--50)"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Heading - Style 5</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Section style 5 (but with extra padding...). And <a href="#">a link</a></p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"flex","orientation":"vertical"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"className":"is-style-pill is-style-text-annotation"} -->
<p class="is-style-pill is-style-text-annotation">Annotation style</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="#">A standard button</a></div>
<!-- /wp:button -->

<!-- wp:button {"className":"is-style-outline"} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link wp-element-button" href="#">An outlined button</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons -->

<!-- wp:quote -->
<blockquote class="wp-block-quote"><!-- wp:paragraph {"style":{"typography":{"writingMode":"horizontal-tb"}}} -->
<p style="writing-mode:horizontal-tb">“Early in my career...I had to choose between an honest <a href="http://blocks.local/section-styles/" data-type="page" data-id="3437">arrogance</a> and a hypercritical humility... I deliberately choose an honest arrogance, and I've never been sorry.”</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"fontSize":"small"} -->
<p class="has-small-font-size">Frank Lloyd Wright</p>
<!-- /wp:paragraph --></blockquote>
<!-- /wp:quote -->

<!-- wp:pullquote -->
<figure class="wp-block-pullquote"><blockquote><p>“Early in my career...I had to choose between an honest <a href="http://blocks.local/section-styles/" data-type="page" data-id="3437">arrogance</a> and a hypercritical humility... I deliberately choose an honest arrogance, and I've never been sorry.”</p><cite>Frank Lloyd Wright</cite></blockquote></figure>
<!-- /wp:pullquote -->

<!-- wp:post-date /--></div>
<!-- /wp:group -->
```

</details>

https://github.com/user-attachments/assets/d94b219f-3adf-4c95-b3d3-ab8cb572121c

**Comment by beafialho** [comment]
Thank you! It's working now, the slight opacity gives it exactly the intended look 🚀 If it's easy, I wonder if we could use the same approach for the code block background? If not, we can just move on.

**Comment by juanfra** [comment]
> Thank you! It's working now, the slight opacity gives it exactly the intended look 🚀 If it's easy, I wonder if we could use the same approach for the code block background? If not, we can just move on.

@beafialho That's not possible on backgrounds, as we're using `currentColor,` which takes the color property.

**Comment by juanfra** [comment]
After discussing this with Carolina and Bea, we're merging it.

**Pull request merged**
