### PR TITLE
Add: CTA book locations and CTA book links patterns.

### PR DESCRIPTION
**Pull request by juanfra**
**Description**

Adding patterns for the "[Landing page: Book](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=3177-1786&m=dev)" page. Adding patterns for the "International" and "book links" sections.

**Screenshots**

https://github.com/user-attachments/assets/bd49a9ed-21f7-4f0a-b15e-8b47401d25bf

https://github.com/user-attachments/assets/bd86ae34-d7fa-47f9-b12a-5ef78f9da546

**Testing Instructions**

1. Create a page.
2. Add the patterns.
3. Confirm they're looking like in the designs.

### CODE REVIEW

**Comment by beafialho** [comment]
Thank you @juanfra these are looking good to me.

The only detail I spotted, the "Call to action with book links" pattern has no side paddings, and therefore is bumping against the edges on mobile:

Captura de ecrã 2024-09-13, às 15 55 43

**Comment by juanfra** [comment]
Thanks @beafialho, good catch. Can you please try again?

**Comment by beafialho** [comment]
I can't seem to see the pattern now 🤔 but looking at the code it seems it has the intended change.

**Comment by juanfra** [comment]
Are you on the `add/cta-book-locations` branch and you pulled the last changes?

**Comment by carolinan** [comment]
Here is what I am seeing, with the padding added:

https://github.com/user-attachments/assets/7cf10367-eab0-4799-bb77-efea301c9c0e

**Pull request merged**
