### PR TITLE
Events - Event schedule pattern design

### PR DESCRIPTION
**Pull request by gohelkunjan**
**Description**

#85 issue will be fixed, once the pattern is merged.

**Screenshots**

image

**Testing Instructions**

### CODE REVIEW

**Comment by juanfra** [comment]
Hi @gohelkunjan - Thank you for working on this. A PR was already open for this issue [here](https://github.com/WordPress/twentytwentyfive/pull/211). 

Maybe you can find ways to collaborate on it or help with other issues?

**Comment by gohelkunjan** [comment]
Okay thank you

**Comment by gohelkunjan** [comment]
So now this issue is done right ?

**Comment by carolinan** [comment]
@gohelkunjan Yes, the pattern is added here: https://github.com/WordPress/twentytwentyfive/blob/trunk/patterns/event-schedule.php

**Pull request closed without merging**
