### PR TITLE
Add: Link in bio with tight margins pattern

### LINKED ISSUE #189: Block Patterns - Landing page -  Link in bio: Image and heading with tight margins
**Description**

🛠️ The goal of this issue is to track the implementation of the `Landing page - Link in bio: Image and heading with tight margins` pattern.
🧑‍💻 The implementation must follow the [pattern creation guidelines](https://github.com/WordPress/twentytwentyfive/blob/trunk/README.md#pattern-creation-guidelines), and should be assigned to its appropriate category.
🎨 [Figma design](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=3177-1789&t=iMHEZ4xZGwCzs1U9-4)

**Original pattern colors** ❌

Captura de ecrã 2024-09-03, às 11 59 52

**Pattern using colors from the existing palette** ✅

Captura de ecrã 2024-09-03, às 17 38 13

### PR DESCRIPTION
**Pull request by beafialho**
**Description**

Adds link in bio with tight margins #189

**Screenshots**

https://github.com/user-attachments/assets/127ec97f-1a53-49f5-b8f0-f61f1337269b

### CODE REVIEW

**Review by juanfra — COMMENTED** [review]
Looks really nice, thanks Bea!

The one thing I noticed is that the social links at the bottom look a bit off in the front-end:

Screenshot 2024-09-04 at 14 49 41

**Comment by beafialho** [comment]
> The one thing I noticed is that the social links at the bottom look a bit off in the front-end:

That's weird. What size is your screen when that shows up? It's looking fine in my front-end.

**Comment by juanfra** [comment]
It's showing like that on all screen sizes. I just checked, and it's happening when viewing the site in Firefox. It's not happening in Chrome.

https://github.com/user-attachments/assets/af4ffc86-fb78-4de3-8e0b-421faca740bd

**Comment by beafialho** [comment]
That's right, I see it on Firefox too. Any suggestions? Could it be an editor bug with Firefox?

**Comment by juanfra** [comment]
> That's right, I see it on Firefox too. Any suggestions? Could it be an editor bug with Firefox?

I've been taking a quick look and it's only happening in Firefox. I found that if I remove the `word-break: break-word;` from the following styles, it works fine.

```
.wp-block-column {
  overflow-wrap: break-word;
  word-break: break-word;
}
```

I believe this issue could use some further investigation. We may want to merge the pattern, so that we have them all merged and then open a new issue to investigate this?

**Comment by beafialho** [comment]
If you think that's the best solution, it works for me, thanks

**Comment by carolinan** [comment]
I looked through the open issues in the Gutenberg repository that has either the columns block, social links label, or the "browser issues" label and I could not find an existing report for this problem.

**Comment by carolinan** [comment]
What about replacing the row with a grid set to manual, with 3 columns? The X has too much spacing on the right, but the order could be changed, or it could be centered.

Firefox on Windows, with the grid used and X centered:
image


```
<!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|20"},"layout":{"selfStretch":"fit","flexSize":null}},"layout":{"type":"grid","columnCount":3,"minimumColumnWidth":null}} -->
<div class="wp-block-group"><!-- wp:paragraph -->
<p><a href="#">Instagram</a></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"align":"center"} -->
<p class="has-text-align-center"><a href="#">X</a></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><a href="#">TikTok</a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
```

**Comment by beafialho** [comment]
Thank you for the suggestion, there's too much spacing between the links in your screenshot

**Comment by carolinan** [comment]
How about this?
(I copied directly from the editor, so it is not cleaned up, the image needs to be replaced)
```
<!-- wp:group {"metadata":{"categories":["twentytwentyfive_page","banner","about","featured"],"patternName":"twentytwentyfive/page-link-in-bio-with-tight-margins","name":"Link in bio with tight margins"},"align":"full","className":"is-style-section-4","style":{"spacing":{"padding":{"top":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|50","right":"var:preset|spacing|50"},"margin":{"top":"0","bottom":"0"}},"dimensions":{"minHeight":"100vh"}},"layout":{"type":"default"}} -->
<div class="wp-block-group alignfull is-style-section-4" style="min-height:100vh;margin-top:0;margin-bottom:0;padding-top:var(--wp--preset--spacing--50);padding-right:var(--wp--preset--spacing--50);padding-bottom:var(--wp--preset--spacing--50);padding-left:var(--wp--preset--spacing--50)"><!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|50"}},"layout":{"type":"grid","columnCount":null,"minimumColumnWidth":"38rem"}} -->
<div class="wp-block-group"><!-- wp:cover {"url":"http://66.local/wp-content/themes/twentytwentyfive/assets/images/link-in-bio-image.webp","alt":"Black and white photo focusing on a woman and a child from afar.","dimRatio":0,"customOverlayColor":"#818181","isUserOverlayColor":true,"minHeight":100,"minHeightUnit":"vh","isDark":false,"style":{"layout":{"selfStretch":"fixed","flexSize":"50%"}},"layout":{"type":"default"}} -->
<div class="wp-block-cover is-light" style="min-height:100vh"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-0 has-background-dim" style="background-color:#818181"></span><img class="wp-block-cover__image-background" alt="Black and white photo focusing on a woman and a child from afar." src="http://66.local/wp-content/themes/twentytwentyfive/assets/images/link-in-bio-image.webp" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:paragraph {"align":"center","fontSize":"large"} -->
<p class="has-text-align-center has-large-font-size"></p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:cover -->

<!-- wp:group {"style":{"dimensions":{"minHeight":"100%"}},"layout":{"type":"flex","orientation":"vertical","verticalAlignment":"space-between"}} -->
<div class="wp-block-group" style="min-height:100%"><!-- wp:paragraph {"align":"left","style":{"typography":{"lineHeight":"1.2"}},"fontSize":"x-large"} -->
<p class="has-text-align-left has-x-large-font-size" style="line-height:1.2">I’m Asahachi Kōno, a Japanese&nbsp;photographer, a member of&nbsp;Los Angeles's Japanese Camera Pictorialists of California. Before returning to Japan, I worked as a photo retoucher.</p>
<!-- /wp:paragraph -->

<!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|20"}},"layout":{"type":"flex","flexWrap":"nowrap"}} -->
<div class="wp-block-group"><!-- wp:paragraph -->
<p><a href="#">Instagram</a></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><a href="#">X</a></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><a href="#">TikTok</a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->
```

**Comment by beafialho** [comment]
> How about this?

Yes, this one looks good to me!

**Comment by juanfra** [comment]
The issue with the social links is working for me now ✨

With the grid, the pattern is looking a bit off on big screens. I could solve it by setting the grid to have two columns, which makes it look off on small screens. So now we have a new different problem.

https://github.com/user-attachments/assets/3b081287-f361-46f9-b1cd-a38e63ddd7b2

**Comment by beafialho** [comment]
Could you both take a look now? I believe I was able to fix it.

**Comment by juanfra** [comment]
I still see the two columns on mobile that I share in [this comment](https://github.com/WordPress/twentytwentyfive/pull/205#issuecomment-2340454201).

**Comment by carolinan** [comment]
Does it need to be a cover block?

**Comment by juanfra** [comment]
I just pushed some changes, to go back using columns, and with a few adjustments, it works now for me in Firefox and Chrome. 

https://github.com/user-attachments/assets/a8f09f1a-e234-4108-8354-98cd8e304c34

@beafialho, can you please confirm it looks good to you?

**Comment by beafialho** [comment]
Thank you @juanfra it looks good to me!

**Comment by juanfra** [comment]
Fantastic, thanks! ✨

**Pull request merged**
