### PR TITLE
Removed Empty line & also remove queryId in several files

### PR DESCRIPTION
**Pull request by shail-mehta**
#### Removed Empty line in below files: 
- patterns/news-blog-archive-template.php
- patterns/photo-blog-archive-template.php
- patterns/photo-blog-home-template.php
- patterns/photo-blog-search-results-template.php

#### Removed `queryId` in below files: 
- patterns/hidden-sidebar.php
- patterns/news-blog-home-template.php

### CODE REVIEW

**Comment by carolinan** [comment]
Because this markup will change many times until it is finalised, is there any way I can motivate you to work on more useful tasks?

**Comment by carolinan** [comment]
For example, if the query loop is updated in the editor, the id will be copy pasted back in, and we will end up removing it over and over. So these tasks are best left to the very end.

**Comment by shail-mehta** [comment]
I completely agree with this point. It’s better to address this task later.

**Comment by shail-mehta** [comment]
> Because this markup will change many times until it is finalised, is there any way I can motivate you to work on more useful tasks?

Yes, I will work on another pattern.

**Pull request closed without merging**
