### PR TITLE
Personal Blog Templates: Text-only alternative

### PR DESCRIPTION
**Pull request by beafialho**
Adds Personal Blog templates (Text-only alternative) listed in #132

Also exported as a zip file.

* [Preview loaded from this PR – available **before** this PR is merged](https://playground.wordpress.net/?import-site=https%3A%2F%2Fraw.githubusercontent.com%2FWordPress%2Ftwentytwentyfive%2Fplayground-changes-2024-08-27T17-22-09-252Z%2Ftwentytwentyfive%2Fplayground.zip)
* [Preview loaded from the main branch – available **after** this PR is merged](https://playground.wordpress.net/?import-site=https%3A%2F%2Fraw.githubusercontent.com%2FWordPress%2Ftwentytwentyfive%2Ftrunk%2Ftwentytwentyfive%2Fplayground.zip)

### CODE REVIEW

**Comment by beafialho** [comment]
I don't have permissions to request a review, but @carolinan @juanfra could you take a look at these templates when you have a chance?

**Comment by carolinan** [comment]
I believe these are the added files? They ended up in the wrong folder.

templates/wp-custom-template-text-only-archive.html
templates/wp-custom-template-text-only-blog.html
templates/wp-custom-template-text-only-post.html
templates/wp-custom-template-text-only-search-results.html

Update:  found the pattern too 
patterns/wp-custom-template-text-only-blog.php

But are there any changes to global styles? (that the plugin would have copied into theme.json)
I can't see right away since there is no file comparison because of the folder problem.

**Comment by beafialho** [comment]
I haven't changed anything in global styles, I have only created the templates and the pattern for the query loop. Oh nice I just see you found the pattern.

**Comment by carolinan** [comment]
I am moving the html files into pattern files right now, but I think the query loop block is missing, I think it is only referenced as
`<!-- wp:block {"ref":2642} /-->`

**Comment by carolinan** [comment]
Do you still have the query in the editor? Can you copy and paste it here?

**Comment by beafialho** [comment]
Yes, here is the code of the pattern.

I can paste the code of the patterns in the next set of templates when I export as a PR as well.

```<!-- wp:query {"queryId":29,"query":{"perPage":10,"pages":0,"offset":0,"postType":"post","order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"","inherit":true,"taxQuery":null,"parents":[]},"align":"wide","layout":{"type":"default"}} -->
<div class="wp-block-query alignwide"><!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:query-no-results {"align":"wide","fontSize":"small"} -->
<!-- wp:spacer {"height":"var:preset|spacing|30"} -->
<div style="height:var(--wp--preset--spacing--30)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:paragraph -->
<p>No posts were found.</p>
<!-- /wp:paragraph -->
<!-- /wp:query-no-results --></div>
<!-- /wp:group -->

<!-- wp:post-template {"align":"full","style":{"spacing":{"blockGap":"0"}},"layout":{"type":"default"}} -->
<!-- wp:group {"align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|30","bottom":"var:preset|spacing|30"}},"border":{"bottom":{"color":"var:preset|color|opacity-20","width":"1px"},"top":{},"right":{},"left":{}}},"layout":{"type":"flex","flexWrap":"nowrap","verticalAlignment":"center","justifyContent":"space-between"}} -->
<div class="wp-block-group alignfull" style="border-bottom-color:var(--wp--preset--color--opacity-20);border-bottom-width:1px;padding-top:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--30)"><!-- wp:post-title {"isLink":true,"fontSize":"medium"} /-->

<!-- wp:post-date {"textAlign":"right","isLink":true,"fontSize":"x-small"} /--></div>
<!-- /wp:group -->
<!-- /wp:post-template --></div>
<!-- /wp:query -->```

**Comment by carolinan** [comment]
The first part of the query loop block is missing, the part with the settings.

**Comment by carolinan** [comment]
Replaced by https://github.com/WordPress/twentytwentyfive/pull/145

**Pull request closed without merging**
