### PR TITLE
Try: Reduce image size.

### PR DESCRIPTION
**Pull request by juanfra**
**Description**

Trying to reduce the image size for several patterns so that the theme zip is lighter.

**Screenshots**

N/A

**Testing Instructions**

404 page
1. Visit the theme 404 page, confirm that the image has good quality.

Patterns:

1. Create a page
2. Add the patterns: Poster-like section, "Overlapping image on the right", "Banner with description and images grid", "About: Image on the right, heading and paragraph", "Events: 3 columns with event images and title", "Link in Bio: Image and heading with tight margins"
3. Confirm that the images maintain good quality.

### CODE REVIEW

**Comment by troychaplin** [comment]
@juanfra these all look great but for some reason the image in the `Link in Bio` pattern is not loading even though the image is showing correctly in the editor sidebar, and checking the direct URL works fine too -- https://playground.wordpress.net/scope:honest-peaceful-park/wp-content/themes/twentytwentyfive-try-reduce-image-size/assets/images/link-in-bio-image.webp

Screenshot 2024-10-21 at 12 23 59 PM

**Comment by juanfra** [comment]
@troychaplin that was a regression that was fixed in Gutenberg [here](https://github.com/WordPress/gutenberg/issues/66067). Can you please check with latest Gutenberg?

**Comment by troychaplin** [comment]
> @troychaplin that was a regression that was fixed in Gutenberg [here](https://github.com/WordPress/gutenberg/issues/66067). Can you please check with latest Gutenberg?

Will try locally, this was on the playground build

**Comment by troychaplin** [comment]
@juanfra all good locally, don't see much difference in the quality of these images

**Comment by juanfra** [comment]
Thank you Troy, I'm merging this one 🚀

**Pull request merged**
