### PR TITLE
Add 404 template with pattern

### PR DESCRIPTION
**Pull request by carolinan**
**Description**
This replaces https://github.com/WordPress/twentytwentyfive/pull/56 _ only because I was not able to pull down the changes._

I made the following changes:
- Renamed the image file, only removing the` -jpeg` that was at the end of the name, since the theme will use the webp.
- Added a wrapping group block and made the columns wide, as seen in the recording on the original Pr.
- I changed the heading to H1, which meant I needed to hard code the font size value to match the size of the H2 heading.

### CODE REVIEW

**Comment by cliffralessio** [comment]
Ok perfect @carolinan  But will I now result on the list of contributors to this project?

**Comment by carolinan** [comment]
yes!

**Comment by carolinan** [comment]
I copied all the credits from the previous PR.

**Comment by cliffralessio** [comment]
Thank you!

**Pull request merged**
