### PR TITLE
Add: Events – List with Call to Action

### LINKED ISSUE #83: Block Patterns - Events - List of events with call to action
**Description**

🛠️ The goal of this issue is to track the implementation of the `Events - List of events with call to action` pattern. 
🧑‍💻 The implementation must follow the [pattern creation guidelines](https://github.com/WordPress/twentytwentyfive/blob/trunk/README.md#pattern-creation-guidelines), and should be assigned to its appropriate category.
🎨 [Figma design](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=3177-1802&t=IqDHO3nwfV13Hcvm-1)

Events_ List of events with call to action

### PR DESCRIPTION
**Pull request by graylaurenm**
**Description**

Adds "Block Patterns - Events - List of events with call to action" #83 

**Screenshots**

[Screen Recording at 2024-09-02 at 12-15-54.webm](https://github.com/user-attachments/assets/43d6c239-1c31-4411-be35-84f887917252)

### CODE REVIEW

**Comment by carolinan** [comment]
Hi!
I think the block needs a full width wrapper so that it matches the width and behavior of other patterns when the user adds a background color. Here is a comparison to one of the other patterns with background color added:

image

--- 
All heading levels are the same, the main heading, "Upcoming events" should be one level higher than the others.
You can increase its level, or decrease the level of the event names.

"Upcoming events" should be larger. In Figma 48px is used.

---
There needs to be an empty blank line at the end of the file.

**Comment by graylaurenm** [comment]
Thank you for this review, Carolina. I have:
1. added the full-width wrapper
2. fixed the incorrect h3 to an h2
3. added the blank line to the end of the file

**Comment by carolinan** [comment]
Hi, I have one small nit, the references to `is-style-default` can be removed,

**Comment by carolinan** [comment]
Thank you!

**Pull request merged**
