### PR TITLE
Try to match noon and typography preset-1

### PR DESCRIPTION
**Pull request by carolinan**
**Description**
Partial for https://github.com/WordPress/twentytwentyfive/issues/423

## Typography

I copied the font size **setting** from Noon to preset 1.
I copied the body font size **style** from Noon to preset 1.
I copied the block typography **styles** from Noon to preset 1
I copied the element typography **styles** from Noon to preset 1

I changed the format in Noon to use "pipes":  
```
- "fontSize": "var(--wp--preset--font-size--medium)",
+ "fontSize": "var:preset|font-size|medium",
```

**Testing Instructions**
Compare the typography settings and styles in the two files, they should match.
Look for any typography settings or styles that are duplicates, that are the same as in theme.json.

## Color

I copied the entire styles section from the combined 02-Noon to the color preset 02-Noon, and from there, removed anything that was not color related.

### Buttons
I removed the hover styles and added the color-mix to two sections.

### CODE REVIEW

**Comment by carolinan** [comment]
I can see why the heading sizes needs to be one size larger than the defaults from theme.json.
I don't have a strong opinion, but the jump in size from h1 to h2 is rather large?

H1 is 58px, (`clamp(2.625rem, 2.625rem +((1vw - 0.2rem)* 1.569), 3.625rem);`)
H2 is 32 (`clamp(1.75rem, 1.75rem +((1vw - 0.2rem)* 0.392), 2rem);`)
image

Compared with the sizes in Figma:
H1 is 42px
H2 is 28.8px
image

**Comment by carolinan** [comment]
This does not look good **in my opinion**. This is from the default single post template:
image

"Written by" is a paragraph and uses Literata, inherited from the body.
The post term uses Beiruti, because in the original Figma design, Beiruti is used for the post **tags** that are below the post
content.

In Figma, the whole line uses Beiruti, font size 20px; https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=77-584&t=U5e7KtwXbVErNU0v-4

**Comment by carolinan** [comment]
On the default home template, the post title is set to X-large in the markup.
Is it too small?

image

**Comment by carolinan** [comment]
There are two ways to sort the section styles from light to dark:
- Update the order of the colors in the palette
- Override the colors in each section style, under styles > variations

Do we want to do either of these?

**Comment by jasmussen** [comment]
This works well for me:

changes

**Pull request merged**
