### PR TITLE
Try: Remove wrappers from landing pages, and set zero margin to individual patterns.

### LINKED ISSUE #664: Full page patterns have redundant nested groups which makes section styles unpredictable
**Description**

The default full page patterns have multiple nested redundant groups. This conflicts with zoom out mode and section styles, which is best described first visually in this GIF:

Image

**Step-by-step reproduction instructions**

1. Go to site editor.
2. Create a NEW page, give it any title.
3. Choose the "Business homepage" pattern.
4. Click a section to change the section style to a different color.
5. Now zoom out, observe how a different section style is chosen, and choosing a new section style isn't actually applied.

What happens here is that zoom out mode works with top level sections, allowing you to select only those. Which means if there's a wrapper group that is _not_ the source of the section style, then there will be a perceived invisible disconnect, as the section style you just applied is one level deeper, on a block no longer selected.

**Expected behavior**

If I set a section style not zoomed out, then zoom out, I should see the same section style. Ideally, we can remove the redundant wrapper groups. Observe in this screenshot, for example, how the "fleurs co" pattern has two wrapping groups:

 Image

Because of the two groups, when you click not zoomed in, you'll select the most nested one. But if you click when zoomed out, you'll select the _least_ nested one. 

**Environment info**

6.7-rc2

### PR DESCRIPTION
**Pull request by juanfra**
**Description**

Fixes https://github.com/WordPress/twentytwentyfive/issues/664

We're removing the wrappers of the landing pages, so that they're functional in the zoom out view. To respect the designs, we are also setting a zero margin to the patterns that are involved in these landing pages.

**Screenshots**

https://github.com/user-attachments/assets/9dde23f0-0844-4e21-a565-ab01c0e4d8e8

**Testing Instructions**

1. Create a page.
2. Insert a landing page. Choose from: "Shop homepage", "Business homepage", "Landing page for book", "Landing page for event", "Landing page for podcast".
3. Confirm that the design is ok.
4. Confirm that the styles of the main sections of the landing pages are accessible in zoom out view.

Repeat again, creating a page from the site editor.

### CODE REVIEW

**Review by jasmussen — APPROVED** [review]
Thanks for this, this works well for me:







It simplifies all the patterns to have a more basic nesting structure, and in the process it also ensures that selecting a section and applying a section style works the same, and as expected, whether you're zoomed or not!

**Comment by richtabor** [comment]
What do you think about applying margin 0 for any fullwidth patterns that can be inserted? That way they all work the same, and you don't end up with this: 

CleanShot 2024-11-05 at 09 39 56

**Comment by jasmussen** [comment]
> What do you think about applying margin 0 for any fullwidth patterns that can be inserted? That way they all work the same, and you don't end up with this:

I'd support that. We'd still need the fewer wrappers, but it could simplify the code, no?

**Comment by juanfra** [comment]
> What do you think about applying margin 0 for any fullwidth patterns that can be inserted? That way they all work the same, and you don't end up with this:

@richtabor @jasmussen the problem with setting all of them to zero is that the layout setting for block spacing won't affect any pattern.

**Comment by jasmussen** [comment]
> the problem with setting all of them to zero is that the layout setting for block spacing won't affect any pattern.

I think that's fine, it will still affect paragraphs and other bits and pieces. I don't think there's an expectation that this particular property would affect the sections as such.

**Comment by juanfra** [comment]
Ok, I updated the rest of the full width patterns.

**Comment by jasmussen** [comment]
Ship it!

**Pull request merged**
