### PR TITLE
Add theme-utils

### LINKED ISSUE #4: Should this repository use the same utilities as the community themes?
The [community themes](https://github.com/WordPress/community-themes) repository has some custom tools, including this recent update which adds a command to validate theme.json: https://github.com/WordPress/community-themes/pull/221

Would it be beneficial to use the same tools in this repository?
@ajlende @MaggieCabrera

### PR DESCRIPTION
**Pull request by ajlende**
**Description**

Closes #4 

Copied from Automattic/themes since there are some recent changes that haven't made it into WordPress/community-themes yet. I had to make some modifications so that it can work on single-theme repos.

This does not include the modifications that `escape-patterns` would make to files or GitHub Automations to run validation on PRs.

Difference from WordPress/community-themes:

- Names of npm scripts
  - **`lint:theme`**: Instead of `patterns:escape` in community-themes
  - **`lint:patterns:fix`**: Instead of `schema:validate` in community-themes
- `escape-patterns` runs on all patterns instead of only modified files. (See `node theme-utils.mjs help escape-patterns` for instructions to run on only modified files.)

**Testing Instructions**

Don't forget to `npm install` as there are some new dev dependencies.

Run both commands
- `npm run lint:theme`
- `npm run lint:patterns:fix`

Verify issues/changes reported are correct.

### CODE REVIEW

**Comment by juanfra** [comment]
Thanks for working on this, Alex. We already have a PR for escaping the patterns [here](https://github.com/WordPress/twentytwentyfive/pull/336). Maybe we should go with this one given that it also has the validate theme functionality.

**Comment by ajlende** [comment]
> Thanks for working on this, Alex. We already have a PR for escaping the patterns [here](https://github.com/WordPress/twentytwentyfive/pull/336). Maybe we should go with this one given that it also has the validate theme functionality.

Sorry @juanfra I didn't see that you already had that one open 😅 

Would you be willing to give this one a test to make sure things are working as expected with my modifications?

**Comment by juanfra** [comment]
> Sorry @juanfra I didn't see that you already had that one open 😅

No problem @ajlende! Thank you for working on this.

> Would you be willing to give this one a test to make sure things are working as expected with my modifications?

I've tested this one, and it is not working for me.


https://github.com/user-attachments/assets/cce25600-6335-47e2-8712-350ecf2e9fdd

**Comment by ajlende** [comment]
@juanfra Thanks for testing! That issue should be fixed now. Give it another try.

**Review by juanfra — APPROVED** [review]
Thanks @ajlende - works like a charm 🏅

**Pull request merged**
