### PR TITLE
Add pattern: Contact - Location and directions link

### LINKED ISSUE #62: Block Patterns - Contact -  Location and directions link
**Description**

🛠️ The goal of this issue is to track the implementation of the `Contact - Location and directions link` pattern. 
🧑‍💻 The implementation must follow the [pattern creation guidelines](https://github.com/WordPress/twentytwentyfive/blob/trunk/README.md#pattern-creation-guidelines), and should be assigned to its appropriate category.
🎨 [Figma design](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=3177-1815&t=IqDHO3nwfV13Hcvm-1)

Contact_ Location and directions link

### PR DESCRIPTION
**Pull request by juanfra**
**Description**

Fixes https://github.com/WordPress/twentytwentyfive/issues/62

**Screenshots**

https://github.com/user-attachments/assets/477bde7c-a3cf-444f-9af1-43db77b14a73

**Testing Instructions**

1. Create a page.
2. Add the pattern.
3. Confirm that it's looking like the designs (spacing/colors/image/etc).

### CODE REVIEW

**Comment by huzaifaalmesbah** [comment]
looks good to me.

**Comment by carolinan** [comment]
I updated the PR from trunk to be able to test the pattern in the current default templates.
There is some extra spacing on the right.
In the editor, this is only visible when both sidebars are closed.
I think this can be fixed by setting "Inner blocks use content width" to false on the outer group block.

**Review by kafleg — APPROVED** [review]
Design wise, it is looking good.

**Comment by carolinan** [comment]
> Design wise, it is looking good.

Do you not see the extra spacing mentioned above? 🤔

**Comment by juanfra** [comment]
Thanks for the reviews!

@carolinan, thanks for the heads-up. I was testing on my laptop, and now, with the external screen I can see what you highlighted. Can you please take a look at the changes? Thanks in advance.

**Comment by carolinan** [comment]
By centering, the spacing on the sides is even, but it is also larger than expected.

**Comment by juanfra** [comment]
@carolinan I can't get to see that. Can you please share a screenshot or screencast? 

From what I see in Figma, the pattern should have a layout where the max-width is "site wide". This means that if the site is viewed on large screens, there will be some space on both sides effectively.

**Comment by carolinan** [comment]
That is the issue, the design in Figma clearly has a 50px padding around it, I am not going to be able to second guess the design and how it is intended to be implemented.

**Comment by carolinan** [comment]
I do not see the pattern placed in any page design where it is not full width.

**Comment by juanfra** [comment]
I believe the `50px` is the standard padding of these types of patterns on a full-width scenario, where the width goes to `1340px`. 

That's how I [understand it](https://github.com/WordPress/twentytwentyfive/pull/129#issuecomment-2312291056), and how it goes in line with how we implemented footers and headers.

@beafialho can you please look at this PR when you have time?

**Comment by beafialho** [comment]
Thank you @juanfra, this pattern is looking good, I see no issues with it.

**Pull request merged**
