### PR TITLE
Hero Podcast Pattern

### PR DESCRIPTION
**Pull request by eirichmond**
**Description**

contribution of Podcast pattern

**Screenshots**

https://github.com/user-attachments/assets/d0a64599-6655-4e78-9558-35e48f40e295

**Testing Instructions**
Create page
Add Hero Podcast pattern from banner section
Test desktop, tablet and mobile

### CODE REVIEW

**Comment by carolinan** [comment]
Hi, this pattern is already being worked on here: https://github.com/WordPress/twentytwentyfive/pull/124
perhaps you can find ways to collaborate on it.

**Comment by eirichmond** [comment]
@carolinan oh ok, sure.

**Comment by eirichmond** [comment]
@carolinan if its already covered, is there something else that might take priority that I can help with instead?

**Comment by carolinan** [comment]
How about this one? https://github.com/WordPress/twentytwentyfive/issues/221

**Pull request closed without merging**
