### PR TITLE
Style quote and pull quote according to the design in theme.json

### LINKED ISSUE #213: The Pull-quote block have extra padding on top & bottom
**Description**
Hello,

I have reviewed the "Pull-quote" block and found that there is extra white space displaying at top & bottom of the block on both editor side & front-end side. I think that it should be little bit, Not that much.

**Step-by-step reproduction instructions**

- Go to admin and select the "Pull-quote" block first.
- Add its paragraph text & citation text.
- Set it border to see it more clear.
- Update the page and check its admin text and front-end text.

**Expected behavior**
I think that the white space it should be little bit, Not that much.

**Here, I have provided screenshot for expected behaviour**
after-resolve-twenty-twenty-five-pull-quote-editor-side
after-resolved-twenty-twenty-five-pull-quote-front-end

**Screenshots**
twenty-twenty-five-pull-quote-editor-side
twenty-twenty-five-pull-quote-front-end

**Environment info**

- Device: Macbook M1
- OS: 14.6.1 (23G93)
- Browser: Google Chrome
- Version 128.0.6613.114 (Official Build) (arm64)
- WordPress version: 6.6.1 running, Gutenberg 19.1.0 , Theme active: Twenty Twenty-Five,

**Additional context**
I have tested this issue with active and inactive Gutenberg plugin and I am getting this issue.

### PR DESCRIPTION
**Pull request by beafialho**
**Description**

This adjustment attempts to style the quote and pullquote blocks in theme.json to match the intended design. 

**Screenshots**

| Before | After |
| ---- | ---- |
| Captura de ecrã 2024-09-06, às 12 32 38 | Captura de ecrã 2024-09-06, às 12 32 43 |

### CODE REVIEW

**Review by juanfra — COMMENTED** [review]
Thanks, Bea! I see that the font sizes have been adjusted but locally the spacing seems a bit off. I'm also running Gutenberg in my test site.

https://github.com/user-attachments/assets/cca9cf15-a440-4b36-bb7b-e7d3276e2e2b

I'll update the spacing here for you to test out.

**Comment by beafialho** [comment]
Ugh, yeah that's too much spacing. I didn't change any of it, I have no idea why it's looking like that.

**Comment by juanfra** [comment]
It seems that those are being inherited from the default ones. I've adjusted some values and it looks like this:

https://github.com/user-attachments/assets/fa14fc1f-45ee-4be9-bf06-23d3d540cf12

Can you please check how they work for you? Thanks

**Comment by beafialho** [comment]
It's looking good on my end:


https://github.com/user-attachments/assets/709eedcb-b534-47ca-a693-72ddec958065

**Comment by juanfra** [comment]
Thanks for looking Bea, I'll merge then.

**Pull request merged**
