### PR TITLE
Try variable fonts as a means to reduce package size

### PR DESCRIPTION
**Pull request by carolinan**
**Description**

Partial for https://github.com/WordPress/twentytwentyfive/issues/401.
By replacing the separate font files with a single variable font, the package size can be decreased somewhat, and the size of theme.json is decreased as well.

**Testing Instructions**

Test the typography preset that uses the updated font families:
Manrope
Fira code
Platypi
Vollkorn
Ysabeau Office

Check that any visual changes are acceptable, since there may be some minor differences in the two formats.
Conform that the correct font style settings are available in the Typography panel > Appearance

### CODE REVIEW

**Review by juanfra — COMMENTED** [review]
Thank you Carolina, from what I tested it looks good.

**Comment by beafialho** [comment]
Thank you for making this change! If my testing is showing accurately, these are looking similar to the previous ones to me. Just to confirm, do they look like the screenshots below to you as well? If so, this is ok to merge.

Captura de ecrã 2024-10-23, às 09 29 44
Captura de ecrã 2024-10-23, às 09 32 15
Captura de ecrã 2024-10-23, às 09 31 10

**Comment by juanfra** [comment]
Yes, it is looking like the screenshots to me. I'm merging this one then.

**Comment by juanfra** [comment]
Thank you all!

**Pull request merged**
