### PR TITLE
theme.json missing all templateParts of parts folder.

### PR DESCRIPTION
**Pull request by noruzzamans**
add missing templateParts from the parts folder to theme.json

### CODE REVIEW

**Comment by carolinan** [comment]
Thank you for working on this. Please remove the unrelated PHP file.

**Comment by noruzzamans** [comment]
> Thank you for working on this. Please remove the unrelated PHP file.

@carolinan I have removed the unrelated PHP file. Please review and let me know if any changes are needed.

**Comment by carolinan** [comment]
I am seeing this PHP notice in the Site Editor: `"sidebar" is not a supported wp_template_part area value`.

Please use the area `uncategorized` instead of `sidebar`.

**Comment by noruzzamans** [comment]
> I am seeing this PHP notice in the Site Editor: `"sidebar" is not a supported wp_template_part area value`.
> 
> Please use the area `uncategorized` instead of `sidebar`.

@carolinan I have resolved these issues. Please review and let me know if any further changes are needed. Thanks

**Pull request merged**
