### PR TITLE
Added font license in readme file

### PR DESCRIPTION
**Pull request by kafleg**
Added font license in the readme file.

### CODE REVIEW

**Comment by aaronjorbin** [comment]
I think this should be a part of #35 rather than a separate PR.

**Comment by juanfra** [comment]
Thanks for working on this!

I agree with Aaron; it would be easier to track all the changes in one PR. 

@kafleg could you please add these changes to https://github.com/WordPress/twentytwentyfive/pull/35 so we track these two in one?

**Comment by kafleg** [comment]
@juanfra Font license is added on #35 so I'm going to close this PR.

**Comment by juanfra** [comment]
Thank you, @kafleg!

**Pull request closed without merging**
