### PR TITLE
Multiple templates: Fix underline inconsistencies

### PR DESCRIPTION
**Pull request by carolinan**
**Description**
Partial for: https://github.com/WordPress/twentytwentyfive/issues/495

## Default single post template
- Enables the underline typography setting on the terms block, in the markup of the template.
- Moves the color definition from the two paragraphs to the wrapping group block.

**Screenshots**
After: Both links are underlined by default.
image

**Testing Instructions**
View the default single post template and confirm if both the author name and category are underlined by default.
Confirm if the heme matches [the design in Figma.](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=3326-1728&t=GUAp7xV6mAMGjrcI-4)

## Photo blog single post template
By changing the default text decoration on the post author name block to "none", in theme.json, the theme matches Figma.

**Screenshots**
After: the link is not underlined by default.
image
⚠️  **NOTE: This matches the design, but the link is invisible to sighted users. It is not accessible. The link can only by found by users who will make assumptions and recognize the pattern of the author name and category being linked.

**Testing Instructions**
View the photo blog single post template and confirm that the author name is not underlined by default.

## News blog single post template
The author name and avatar were not linked. The links were added to make the template more consistent with the other templates.

⚠️  To match Figma, no underline was added.  A sighted user will only find the links if they recognize the pattern of the author name being linked (and goes to try it).

image

**Testing Instructions**
View the News blog single post template and confirm that the author name and avatar are linked to the author's user profile.

## Right-aligned blog with vertical header, single post template
The author name and avatar were not linked. The links were added to make the template more consistent with the other templates.

⚠️  To match Figma, no underline was added.  A sighted user will only find the links if they recognize the pattern of the author name being linked (and goes to try it).

image

**Testing Instructions**
View the single post template for the right-aligned blog, and confirm that the author name and avatar are linked to the author's user profile.

### CODE REVIEW

**Comment by carolinan** [comment]
I already added this comment on the issue, but perhaps it is more visible here:

Could the "in" in the "Written by..." on the default single post be removed? It is making the string difficult to translate because it has four separate parts with the block markup included.
Perhaps the middle dot separator could be used between the username and the category?

**Comment by beafialho** [comment]
Thank you for working on the inconsistencies @carolinan. The "in" should be kept, ideally.

**Default single post template**: looks good ✅
**Photo blog single post template**: looks good ✅

The other two, could you share a screenshot of what it's looking like for you? I'm not sure I'm seeing the same.

**Comment by carolinan** [comment]
Yes, of course. I will add them to the PR description.

**Comment by beafialho** [comment]
Thank you! The other two look good as well.

**Pull request merged**
