### PR TITLE
Move the color palette presets to a subfolder under styles

### PR DESCRIPTION
**Pull request by carolinan**
**Description**
The color palette presets are placed directly in the styles folder.
Once the "combined" style variation files are added, the number of JSON files in the styles folder will be doubled.
This PR moves the color palette presets to a separate folder, to organize the files and make the long term maintenance of the JSON files easier.

Partial for: https://github.com/WordPress/twentytwentyfive/issues/193

**Testing Instructions**
Go to Appearance > Editor > Styles and confirm that the palette presets are still available in the Site Editor.

### CODE REVIEW

**Review by juanfra — COMMENTED** [review]
Thanks Carolina. It's working well for me.

Not sure if we want to prefix them with a number like it's done [here](https://github.com/Automattic/themes/tree/trunk/assembler/styles/colors) or not.

**Comment by carolinan** [comment]
Me neither, I don't have a preference for or against🤔

**Comment by carolinan** [comment]
Should they be named color-preset-1, color-preset-2 perhaps

**Comment by juanfra** [comment]
I believe the number prefixes are to indicate the order in which they're displayed; if not, they display in alphabetical order.

@beafialho do you have any preference about the order in which the palettes are being listed? Would you like for us to follow the order in the Figma file?

If we don't have a preference with the order, this one should be good to merge.

**Comment by carolinan** [comment]
@beafialho do you have any preference about the order in which the palettes are being listed?

**Comment by beafialho** [comment]
Apologies, I must have missed this ping.

My preference is the order in which they are listed in Figma:

**1. Default
2. Evening
3. Noon
4. Dusk
5. Afternoon
6. Twilight
7. Morning
8. Sunrise
9. Midnight**

**Pull request merged**
