### PR TITLE
Add: Landing page for book.

### PR DESCRIPTION
**Pull request by juanfra**
**Description**

Adding landing page for book. [Figma link](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=3177-1786&m=dev).

**Screenshots**

https://github.com/user-attachments/assets/1ad19b18-dd30-4918-8cc9-641ec3e85cf7

**Testing Instructions**

1. Create a page.
2. Select the Landing page book and confirm that it's using the correct patterns and in the same order

### CODE REVIEW

**Comment by beafialho** [comment]
Thank you @juanfra it's looking great! It's exciting to see the patterns working in the landing pages ✨

I noticed a bit too much spacing below the first group, perhaps due to the minimum height setting:

https://github.com/user-attachments/assets/099c2ab6-e0fa-4638-a26a-8ed843611b6b

And two other small details related with the patterns themselves (if we can address them in this PR):

- _"About the Book"_ has a capital "B" let's replace it with _"About the book"_ (only here)
- Add `XL font size` preset to the _"Frequently Asked Questions"_ heading, to be consistent with the other headings of the patterns in the page

**Comment by juanfra** [comment]
Thanks for the quick review @beafialho 

I changed the min-height, and removed the capital B. 

Regarding the FAQ title, I'd have to do that at a pattern level, affecting the size wherever the pattern is used. Let me know if you're ok with that or if you want to review how it looks in other places first. Or if you're ok with keeping the size of the title, how it was designed in Figma, and how it is implemented now.

**Comment by beafialho** [comment]
Thanks, I'm ok with applying that size to the heading.

**Comment by juanfra** [comment]
@beafialho ok - updated. Thanks

**Comment by beafialho** [comment]
Thank you for the update!

Sorry but I just noticed, it would be nice if we grouped all the patterns and named the group "Book Landing Page" for consistency with the others? Also might be a good idea to add `0` Block spacing to that outer group.

Captura de ecrã 2024-09-17, às 15 55 45

After this, it seems good to merge.

**Comment by carolinan** [comment]
We can add the wrapping group with the block spacing 0 as part of https://github.com/WordPress/twentytwentyfive/issues/328

**Pull request merged**
