### PR TITLE
Try: Reduce the number of groups in landing pages to improve zoom out experience.

### LINKED ISSUE #664: Full page patterns have redundant nested groups which makes section styles unpredictable
**Description**

The default full page patterns have multiple nested redundant groups. This conflicts with zoom out mode and section styles, which is best described first visually in this GIF:

Image

**Step-by-step reproduction instructions**

1. Go to site editor.
2. Create a NEW page, give it any title.
3. Choose the "Business homepage" pattern.
4. Click a section to change the section style to a different color.
5. Now zoom out, observe how a different section style is chosen, and choosing a new section style isn't actually applied.

What happens here is that zoom out mode works with top level sections, allowing you to select only those. Which means if there's a wrapper group that is _not_ the source of the section style, then there will be a perceived invisible disconnect, as the section style you just applied is one level deeper, on a block no longer selected.

**Expected behavior**

If I set a section style not zoomed out, then zoom out, I should see the same section style. Ideally, we can remove the redundant wrapper groups. Observe in this screenshot, for example, how the "fleurs co" pattern has two wrapping groups:

 Image

Because of the two groups, when you click not zoomed in, you'll select the most nested one. But if you click when zoomed out, you'll select the _least_ nested one. 

**Environment info**

6.7-rc2

### PR DESCRIPTION
**Pull request by juanfra**
**Description**

Fixes https://github.com/WordPress/twentytwentyfive/issues/664

We're using a `<main>` wrapper for the landing pages with a block gap of zero, so that the different sections are editable in zoom-out view.

**Screenshots**

https://github.com/user-attachments/assets/33da1deb-bdb3-4442-af64-9d58d6a2c91b

**Testing Instructions**

1. Create a page.
2. Insert a landing page. Choose from: "Shop homepage", "Business homepage", "Landing page for book", "Landing page for event", "Landing page for podcast".
3. Confirm that the design is ok.
4. Confirm that the styles of the main sections of the landing pages are accessible in zoom out view.

### CODE REVIEW

**Comment by jasmussen** [comment]
Gave this a quick test in the site editor > pages > new flow, and I'm seeing a different issue there, where only the business homepage can be selected:

2024-11-05 12 53 52 tt5 local 92ff6d758240

I'm also still seeing the redundant groups here:

Screenshot 2024-11-05 at 12 54 35

Did I test things wrong, here? 

Thanks for the PR!

**Comment by juanfra** [comment]
I see. In that flow, the content is already the "main", so we would have two "main" and the fix won't work.

> I'm also still seeing the redundant groups here:

Those are coming from the pattern.

Edit: In the flow of creating a page and inserting the landings, we'll also have the markup with two `<main>` elements and that creates accessibility problems.

**Comment by jasmussen** [comment]
Any instincts, @richtabor ?

**Comment by juanfra** [comment]
Closing in favor of https://github.com/WordPress/twentytwentyfive/pull/669

I also cherry-picked the other fixes and created a PR [here](https://github.com/WordPress/twentytwentyfive/pull/668).

**Pull request closed without merging**
