### PR TITLE
Add two new section styles, and 

### PR DESCRIPTION
**Pull request by jasmussen**
**Description**

Adds two new section styles, fixes a pattern typo, and updates the Clients Section pattern to use section styles.

The two new styles are inspired by these styles in the Figma:

Screenshot 2024-08-30 at 13 01 34

Screenshot 2024-08-30 at 13 01 44

Screenshot 2024-08-30 at 13 01 48

Here's the end results:

state

Separately, an issue has surfaced with the Social Icons block:

icon colors

Basically, since we can't globally style the _icon color_, neither can we section-style the icon color. @getdave if you'll forgive the ping. In case you have time to look, do you know how big of a lift it would be in the editor to add global styles support for the Icon Color?

**Testing Instructions**

Try some patterns, including the "Clients section" pattern, with section styles. Test the new beige and black styles.

### CODE REVIEW

**Comment by jasmussen** [comment]
Would it be possible/reasonable/feasible to, in theme.json, create a new color-swatch that maps to `currentColor` and apply it explicitly for the icon color?

**Comment by carolinan** [comment]
> Would it be possible/reasonable/feasible to, in theme.json, create a new color-swatch that maps to currentColor and apply it explicitly for the icon color?

I have not tried if it works, or what custom CSS that would be needed for adding the color to the icon. 
Or are we expecting currentColor to work in the color **control** too?

**Comment by beafialho** [comment]
This is looking good in my testing, the only issue I saw was the social icons color. Excited that it's working nicely!

**Review by beafialho — APPROVED** [review]

**Comment by jasmussen** [comment]
> Or are we expecting currentColor to work in the color control too?

I think @richtabor suggested that _refs_ is the future forward way to solve this, which I'd tend to agree with, so a swatch that maps to currentColor is mostly theoretical at this point. It works, though, but as should also be clear: it's not a good user experience:

currentColor

**Pull request merged**
