### PR TITLE
Add: Poster-like section pattern

### PR DESCRIPTION
**Pull request by beafialho**
**Description**

Adds poster-like section pattern #82.

I figured this one worked nicely if the content inside it had a wide width, instead of full, see how harmonious it looks when using another pattern below.

**Screenshots**

https://github.com/user-attachments/assets/b89bc7a4-58b2-413f-8897-9ef31e66d155

### CODE REVIEW

**Review by juanfra — APPROVED** [review]
Thanks Bea, it works really well. I agree that it's super nice with the content set to site wide, it works well with the rest.

I've updated the code, added the image and the license for the image. Please give it a try and if everything is ok on your end we should be good to merge.

https://github.com/user-attachments/assets/e2aef2f7-d4f8-4cef-b1fb-0fe31b991b15

**Comment by beafialho** [comment]
@juanfra I can't find the pattern in the patterns sidebar, do you have an idea why that may be happening?

**Comment by juanfra** [comment]
@beafialho it is working for me. Can you check that you're in the right branch? `poster-like-section` is the one you must select, and you should pull the latest changes.

**Comment by beafialho** [comment]
It's working now... Perhaps this is because I was editing a page inside a template. Anyway, this one looks good to merge 👍

**Comment by juanfra** [comment]
That's great; merging this one, then. Thanks!

**Pull request merged**
