### PR TITLE
Add: CV/Bio Pattern

### LINKED ISSUE #174: Block Patterns - Landing Page - CV/Bio
**Description**

🛠️ The goal of this issue is to track the implementation of the `Landing Page - CV/Bio` pattern.
🧑‍💻 The implementation must follow the [pattern creation guidelines](https://github.com/WordPress/twentytwentyfive/blob/trunk/README.md#pattern-creation-guidelines), and should be assigned to its appropriate category.
🎨 [Figma design](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=3177-1785&t=mozS5KE5vWTpKoUs-4)

Captura de ecrã 2024-09-02, às 11 40 19

### PR DESCRIPTION
**Pull request by beafialho**
**Description**

Adds CV/Bio Pattern #174 

**Screenshots**

https://github.com/user-attachments/assets/01665778-97b8-4e2f-9cf9-f377eaaec79d

### CODE REVIEW

**Review by juanfra — COMMENTED** [review]
Thanks Bea! Looks good to me. I've adjusted the code, including the image in the theme and working a bit on the indent. Please double check that everything is looking good for you after these changes.


https://github.com/user-attachments/assets/bc6c0c75-d6e2-4b22-ab60-7a0cdb6da1b0

**Comment by beafialho** [comment]
Thank you @juanfra! The only thing I see is the image (and all the images used in patterns) should use the crop from the Figma file, not without the original photo with the black frames. Can we update that?

**Comment by juanfra** [comment]
Thanks @beafialho!

Sure, I've added the one exported from the pattern. Will keep in mind for other patterns.

**Comment by beafialho** [comment]
@juanfra I noticed you "assigned" this one to me. Is there something left to do?

**Comment by juanfra** [comment]
@beafialho no, I already merged. I assigned to you for organization purposes only and in case you wanted to take a look at the latest changes.

**Comment by beafialho** [comment]
Alright, thanks!

**Pull request merged**
