### PR TITLE
update: removed purple site title link color in dusk theme

### LINKED ISSUE #604: Dusk: Site title is colored
**Description**
The site title for Dusk is purple, but in the design, it's not colored.

**Step-by-step reproduction instructions**
1. Activate the dusk variation.
2. Check the site title color, and confirm it's not like in the designs.

**Expected behavior**

The expectation would be to match the designs.

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by troychaplin**
**Description**

This addresses #604. Removed paragraph link style that impacts site title and compared to other styles, which do not seem to have this link style in place. Some screenshots of how link in a para is treated with just an underline, no specific color treatment.

**Screenshots**

example-2
example-3
example-4
example-1

### CODE REVIEW

**Comment by carolinan** [comment]
This change affects Dusk, but the screenshots are of the other variations.

In the design, the links are supposed to be purple, so this style should not be removed.
https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=77-338&node-type=frame&t=wE2ugqqAeMGWDKJ3-0

Does setting the correct color on styles > Blocks > core/site-title > elements > link not work?

**Comment by troychaplin** [comment]
> This change affects Dusk, but the screenshots are of the other variations.
> 
> In the design, the links are supposed to be purple, so this style should not be removed. https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=77-338&node-type=frame&t=wE2ugqqAeMGWDKJ3-0
> 
> Does setting the correct color on styles > Blocks > core/site-title > elements > link not work?

Oh, then I’ll look at this again today

**Comment by juanfra** [comment]
@troychaplin please let us know if you still have time to iterate on this. Thanks 🙏

**Comment by troychaplin** [comment]
> @troychaplin please let us know if you still have time to iterate on this. Thanks 🙏

Working on it. Can't figure it out, probably missing something easy here 😕

**Comment by carolinan** [comment]
The site title can't override the CSS that WP adds to the link color to the paragraph.

In Dusk, can you try removing the link color from the site title, and adding this directly under styles:
`"css": "p.wp-block-site-title:not(.has-link-color) a { color: var(--wp--preset--color--accent-3);}",`

That way it overrides the link style on the p element, and if the user adds a color in the block setting, that setting works.

**Comment by troychaplin** [comment]
> The site title can't override the CSS that WP adds to the link color to the paragraph.
> 
> In Dusk, can you try removing the link color from the site title, and adding this directly under styles: `"css": "p.wp-block-site-title:not(.has-link-color) a { color: var(--wp--preset--color--accent-3);}",`
> 
> That way it overrides the link style on the p element, and if the user adds a color in the block setting, that setting works.

Thank you! I’ll get back to this one shortly!

**Comment by juanfra** [comment]
@carolinan another reason to try to get the class in the paragraph block 😅

**Comment by troychaplin** [comment]
@carolinan thank you, this worked well and changes have been pushed

**Comment by carolinan** [comment]
There seems to be several changes to the json files that are unrelated to changing the link color on the site title?

**Comment by troychaplin** [comment]
> There seems to be several changes to the json files that are unrelated to changing the link color on the site title?

I just reviewed and one change to colors/dusk was reverted. Other changes to styles/dusk are coming from a merge from trunk into the branch. The key change for this on it around site-title and removing the link element and adding custom css

**Comment by carolinan** [comment]
I don't understand. The underline changes are all unrelated.

**Comment by troychaplin** [comment]
> I don't understand. The underline changes are all unrelated.

I went back to a clean branch to test this out, and either I have something wrong in my local setup, or this issue has been resolved with changes elsewhere. I can't recreate the issue in trunk.

**Comment by juanfra** [comment]
@troychaplin I believe what Carolina is sharing is that if you go to the [files changed](https://github.com/WordPress/twentytwentyfive/pull/610/files) in this PR, you can see that the submission includes different changes that are unrelated to the problem described in the issue:

1. Lines [90-97](https://github.com/WordPress/twentytwentyfive/pull/610/files#diff-424d7ce7d0eba2b0c09e49c130cb86989281e8862e869ff83ab786798659bf11R90-R97)
2. Lines [113-120](https://github.com/WordPress/twentytwentyfive/pull/610/files#diff-424d7ce7d0eba2b0c09e49c130cb86989281e8862e869ff83ab786798659bf11R113-R120)
3. Lines [161-167](https://github.com/WordPress/twentytwentyfive/pull/610/files#diff-424d7ce7d0eba2b0c09e49c130cb86989281e8862e869ff83ab786798659bf11L161-L167)
4. Lines [256-263](https://github.com/WordPress/twentytwentyfive/pull/610/files#diff-424d7ce7d0eba2b0c09e49c130cb86989281e8862e869ff83ab786798659bf11R256-R263)

What would fix the issue is the change in line 180:

```
"css": "p.wp-block-site-title:not(.has-link-color) a { color: var(--wp--preset--color--accent-3);}",
```

**Comment by troychaplin** [comment]
> @troychaplin I believe what Carolina is sharing is that if you go to the [files changed](https://github.com/WordPress/twentytwentyfive/pull/610/files) in this PR, you can see that the submission includes different changes that are unrelated to the problem described in the issue:
> 
>     1. Lines [90-97](https://github.com/WordPress/twentytwentyfive/pull/610/files#diff-424d7ce7d0eba2b0c09e49c130cb86989281e8862e869ff83ab786798659bf11R90-R97)
> 
>     2. Lines [113-120](https://github.com/WordPress/twentytwentyfive/pull/610/files#diff-424d7ce7d0eba2b0c09e49c130cb86989281e8862e869ff83ab786798659bf11R113-R120)
> 
>     3. Lines [161-167](https://github.com/WordPress/twentytwentyfive/pull/610/files#diff-424d7ce7d0eba2b0c09e49c130cb86989281e8862e869ff83ab786798659bf11L161-L167)
> 
>     4. Lines [256-263](https://github.com/WordPress/twentytwentyfive/pull/610/files#diff-424d7ce7d0eba2b0c09e49c130cb86989281e8862e869ff83ab786798659bf11R256-R263)
> 
> 
> What would fix the issue is the change in line 180:
> 
> ```
> "css": "p.wp-block-site-title:not(.has-link-color) a { color: var(--wp--preset--color--accent-3);}",
> ```

Yeah, I'm not sure where those came from. I assumed it was a merge from trunk but no. I went to create a new branch to test and fix properly, but I cannot recreate the purple in site title locally anymore, and I'm not sure if I'm having some odd issues locally, or if this got fixed through CSS work in other areas.

**Comment by juanfra** [comment]
Maybe those come from a merge conflict when updating trunk?

I can still see the issue when checking on trunk.

**Comment by troychaplin** [comment]
> Maybe those come from a merge conflict when updating trunk?
> 
> I can still see the issue when checking on trunk.

Maybe. Might be best to just close this PR out and I'll submit a new one with only the css changes needed

**Comment by troychaplin** [comment]
Ok, so I've reverted back those questionable changes, and have figured out my local issues so I can see these changes properly. Unfortunately adding inline css is not the ultimate fix, not sure what else needs to be done.

I did notice that Sunrise has specific link colours that are not the same as what is being applied to site title, I'll look at differences and see if I can figure out where the issue lies.

**Comment by carolinan** [comment]
> Unfortunately adding inline css is not the ultimate fix, not sure what else needs to be done.

There is nothing else the theme can do under these conditions, since the bug is in the editor.

**Comment by carolinan** [comment]
The dusk **color preset** still uses the old styles, it needs to be updated too.

**Comment by troychaplin** [comment]
> The dusk **color preset** still uses the old styles, it needs to be updated too.

Sorry, haven't had a chance to come back to TT5 lately. So even after the change in the color preset the title remains purple, as you noted. Is this blocked until the issue in the editor relating to classes on the paragraph block is fixed?

**Comment by carolinan** [comment]
Yeah it may require the editor issue with the paragraph block name to be fixed first.
Also I think that `color preset` JSON files might not accept the CSS field. I am not sure if it should.

Either way this would need to be solved outside this repository after the release of 6.7.
So I am closing this PR in preparation of archiving this repository.

**Pull request closed without merging**
